# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

target 'Demo-objc' do
  pod 'YPNavigationBarTransition', :path => '../../YPNavigationBarTransition.podspec'
end

